#!/usr/bin/env bash
# Entrypoint for the backup sidecar.
# Builds /etc/crontabs/root from the BACKUP_CRON env var, then execs crond.
set -euo pipefail

BACKUP_CRON="${BACKUP_CRON:-0 3 * * *}"

# Write the crontab
{
  echo "# Generated by entrypoint at $(date -Iseconds)"
  echo "TZ=${TZ:-UTC}"
  echo "$BACKUP_CRON /scripts/backup.sh > /proc/1/fd/1 2>/proc/1/fd/2"
  echo "# Required empty line"
} > /etc/crontabs/root

chmod 600 /etc/crontabs/root

echo "[backup] crontab: '$BACKUP_CRON' -> /scripts/backup.sh"
echo "[backup] retention: ${BACKUP_KEEP_DAYS:-14} days"

# Hand off to crond
exec crond -f -d 0
